### PR TITLE
Admin functions

### PR DESCRIPTION
**Pull request by jy-clairechoi**
## Description

add and remove functions for event/workshop schedules, FAQ, prizes, and tracks

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
  - [ ] I wrote a design doc: *Replace this with a link to your design doc's short link*
  - [ ] I got input from a developer, specifically from: *Replace with the names of who gave advice*
  - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/bostonhacks/cacioepepe/issues
[Contributor Guide]: https://github.com/bostonhacks/cacioepepe/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rishabnayak** [comment]
@jy-clairechoi please resolve conflicts! also did you get a chance to circle back with @asifrahman479 to figure out how you guys were splitting stuff

**Comment by rishabnayak** [comment]
Also @jfeng5529 looks like @jy-clairechoi did some work on a calendar, please coordinate?

**Comment by jinyoungbang** [comment]
Instead of returning "Completed!", do you mind changing it by returning a code with a msg? I think it'd be much more clearer fo the user calling the functions and it's industry practice as well :) @jy-clairechoi 

https://www.restapitutorial.com/httpstatuscodes.html

**Comment by rishabnayak** [comment]
> Instead of returning "Completed!", do you mind changing it by returning a code with a msg? I think it'd be much more clearer fo the user calling the functions and it's industry practice as well :) @jy-clairechoi
> 
> https://www.restapitutorial.com/httpstatuscodes.html

yup!!

**Pull request merged**
